// <auto-generated />
using System;
using CrudMvcEF.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CrudMvcEF.Migrations
{
    [DbContext(typeof(CrudMvcEFContext))]
    [Migration("20190317150128_OtherEntities")]
    partial class OtherEntities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CrudMvcEF.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<int?>("ClientId");

                    b.Property<string>("State");

                    b.Property<string>("StreetAddress");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("CrudMvcEF.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Cpf");

                    b.Property<string>("Name");

                    b.Property<string>("Rg");

                    b.HasKey("Id");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("CrudMvcEF.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ClientId");

                    b.Property<string>("Email");

                    b.Property<string>("PhoneNumber");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Contact");
                });

            modelBuilder.Entity("CrudMvcEF.Models.Address", b =>
                {
                    b.HasOne("CrudMvcEF.Models.Client", "Client")
                        .WithMany("Addresses")
                        .HasForeignKey("ClientId");
                });

            modelBuilder.Entity("CrudMvcEF.Models.Contact", b =>
                {
                    b.HasOne("CrudMvcEF.Models.Client", "Client")
                        .WithMany("Contacts")
                        .HasForeignKey("ClientId");
                });
#pragma warning restore 612, 618
        }
    }
}
